### ISSUE TITLE
Allow obsolete strings / files to be removed for SeaMonkey

### ISSUE THREAD

**Issue by IanN-GH** [flodolo/fluent-migrations#10]
At the moment SeaMonkey is excluded from obsolete string / file cleanup on l10n central but we would now like it to be included.

**Comment by flodolo** [comment]
@IanN-GH 

I've run both scripts on German (I'll run them for all locales at some point, before the end of this cycle)
* [Empty files](https://hg.mozilla.org/l10n-central/de/rev/62c943673f58c5b0653173d8012a233c2abc5cd2)
* [Obsolete strings](https://hg.mozilla.org/l10n-central/de/rev/4a84a521f3f597235e940320003e5e4fa3d526a5) (unfortunately, this one includes a lot of whitespace changes).

Does that look reasonable to you?

**Comment by IanN-GH** [comment]
Yes, that looks fine.

**Comment by flodolo** [comment]
Thanks, I'll take it for a spin on all locales in the coming days 👍🏼
